//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPE3_GSB_WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class activite_compl
    {
        public activite_compl()
        {
            this.inviters = new HashSet<inviter>();
            this.realisers = new HashSet<realiser>();
        }
    
        public int AC_NUM { get; set; }
        public Nullable<System.DateTime> AC_DATE { get; set; }
        public string AC_LIEU { get; set; }
        public string AC_THEME { get; set; }
        public string AC_MOTIF { get; set; }
    
        public virtual ICollection<inviter> inviters { get; set; }
        public virtual ICollection<realiser> realisers { get; set; }
    }
}
