//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPE3_GSB_WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class composant
    {
        public composant()
        {
            this.constituers = new HashSet<constituer>();
        }
    
        public string CMP_CODE { get; set; }
        public string CMP_LIBELLE { get; set; }
    
        public virtual ICollection<constituer> constituers { get; set; }
    }
}
