//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPE3_GSB_WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class constituer
    {
        public string MED_DEPOTLEGAL { get; set; }
        public string CMP_CODE { get; set; }
        public Nullable<double> CST_QTE { get; set; }
    
        public virtual composant composant { get; set; }
        public virtual medicament medicament { get; set; }
    }
}
