//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPE3_GSB_WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class dosage
    {
        public dosage()
        {
            this.prescrires = new HashSet<prescrire>();
        }
    
        public string DOS_CODE { get; set; }
        public string DOS_QUANTITE { get; set; }
        public string DOS_UNITE { get; set; }
    
        public virtual ICollection<prescrire> prescrires { get; set; }
    }
}
