//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPE3_GSB_WF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GSB_PPE3Entities : DbContext
    {
        public GSB_PPE3Entities()
            : base("name=GSB_PPE3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<activite_compl> activite_compl { get; set; }
        public DbSet<composant> composants { get; set; }
        public DbSet<constituer> constituers { get; set; }
        public DbSet<dosage> dosages { get; set; }
        public DbSet<famille> familles { get; set; }
        public DbSet<inviter> inviters { get; set; }
        public DbSet<medicament> medicaments { get; set; }
        public DbSet<motif> motifs { get; set; }
        public DbSet<offrir> offrirs { get; set; }
        public DbSet<posseder> posseders { get; set; }
        public DbSet<praticien> praticiens { get; set; }
        public DbSet<prescrire> prescrires { get; set; }
        public DbSet<presentation> presentations { get; set; }
        public DbSet<rapport_visite> rapport_visite { get; set; }
        public DbSet<realiser> realisers { get; set; }
        public DbSet<region> regions { get; set; }
        public DbSet<responsable> responsables { get; set; }
        public DbSet<secteur> secteurs { get; set; }
        public DbSet<specialite> specialites { get; set; }
        public DbSet<travailler> travaillers { get; set; }
        public DbSet<type_individu> type_individu { get; set; }
        public DbSet<type_praticien> type_praticien { get; set; }
        public DbSet<visiteur> visiteurs { get; set; }
    }
}
