//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPE3_GSB_WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class offrir
    {
        public string VIS_MATRICULE { get; set; }
        public int RAP_NUM { get; set; }
        public string MED_DEPOTLEGAL { get; set; }
        public Nullable<int> OFF_QTE { get; set; }
    
        public virtual medicament medicament { get; set; }
        public virtual rapport_visite rapport_visite { get; set; }
    }
}
