//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPE3_GSB_WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class posseder
    {
        public int PRA_NUM { get; set; }
        public string SPE_CODE { get; set; }
        public string POS_DIPLOME { get; set; }
        public Nullable<double> POS_COEFPRESCRIPTION { get; set; }
    
        public virtual specialite specialite { get; set; }
        public virtual praticien praticien { get; set; }
    }
}
