//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPE3_GSB_WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class prescrire
    {
        public string MED_DEPOTLEGAL { get; set; }
        public string TIN_CODE { get; set; }
        public string DOS_CODE { get; set; }
        public string PRE_POSOLOGIE { get; set; }
    
        public virtual dosage dosage { get; set; }
        public virtual medicament medicament { get; set; }
        public virtual type_individu type_individu { get; set; }
    }
}
