//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPE3_GSB_WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class secteur
    {
        public secteur()
        {
            this.regions = new HashSet<region>();
            this.responsables = new HashSet<responsable>();
        }
    
        public string SEC_CODE { get; set; }
        public string SEC_LIBELLE { get; set; }
    
        public virtual ICollection<region> regions { get; set; }
        public virtual ICollection<responsable> responsables { get; set; }
    }
}
