//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPE3_GSB_WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class type_praticien
    {
        public type_praticien()
        {
            this.praticiens = new HashSet<praticien>();
        }
    
        public string TYP_CODE { get; set; }
        public string TYP_LIBELLE { get; set; }
        public string TYP_LIEU { get; set; }
    
        public virtual ICollection<praticien> praticiens { get; set; }
    }
}
