//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPE3_GSB_WF.Accès_aux_données
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GSB_PPE3Entities1 : DbContext
    {
        public GSB_PPE3Entities1()
            : base("name=GSB_PPE3Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<activite_compl> activite_compl { get; set; }
        public virtual DbSet<composant> composants { get; set; }
        public virtual DbSet<constituer> constituers { get; set; }
        public virtual DbSet<dosage> dosages { get; set; }
        public virtual DbSet<famille> familles { get; set; }
        public virtual DbSet<inviter> inviters { get; set; }
        public virtual DbSet<medicament> medicaments { get; set; }
        public virtual DbSet<motif> motifs { get; set; }
        public virtual DbSet<offrir> offrirs { get; set; }
        public virtual DbSet<posseder> posseders { get; set; }
        public virtual DbSet<praticien> praticiens { get; set; }
        public virtual DbSet<prescrire> prescrires { get; set; }
        public virtual DbSet<presentation> presentations { get; set; }
        public virtual DbSet<rapport_visite> rapport_visite { get; set; }
        public virtual DbSet<realiser> realisers { get; set; }
        public virtual DbSet<region> regions { get; set; }
        public virtual DbSet<responsable> responsables { get; set; }
        public virtual DbSet<secteur> secteurs { get; set; }
        public virtual DbSet<specialite> specialites { get; set; }
        public virtual DbSet<type_individu> type_individu { get; set; }
        public virtual DbSet<type_praticien> type_praticien { get; set; }
        public virtual DbSet<visiteur> visiteurs { get; set; }
    }
}
