//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPE3_GSB_WF.Accès_aux_données
{
    using System;
    using System.Collections.Generic;
    
    public partial class responsable
    {
        public string RES_MATRICULE { get; set; }
        public string SEC_CODE { get; set; }
    
        public virtual visiteur visiteur { get; set; }
        public virtual secteur secteur { get; set; }
    }
}
