//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPE3_GSB_WF.Accès_aux_données
{
    using System;
    using System.Collections.Generic;
    
    public partial class visiteur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public visiteur()
        {
            this.rapport_visite = new HashSet<rapport_visite>();
            this.realisers = new HashSet<realiser>();
            this.travaillers = new HashSet<travailler>();
        }
    
        public string VIS_MATRICULE { get; set; }
        public string VIS_NOM { get; set; }
        public string VIS_PRENOM { get; set; }
        public string VIS_ADRESSE { get; set; }
        public string VIS_CP { get; set; }
        public string VIS_VILLE { get; set; }
        public Nullable<System.DateTime> VIS_DATEEMBAUCHE { get; set; }
        public string VIS_LOGIN { get; set; }
        public string VIS_MDP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rapport_visite> rapport_visite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<realiser> realisers { get; set; }
        public virtual responsable responsable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<travailler> travaillers { get; set; }
        public virtual region region { get; set; }
    }
}
